export const baseUrl = 'http://pinnacle.test'
    // export const baseUrl = 'https://api.pinnacleonline.org'
export const tokenVariable = 'P_access_token'
export const cloudName = 'charisbiz-africa'
export const upload_preset = 'qtwirqod'